### ISSUE TITLE
Use example with browserify

### ISSUE THREAD

**Issue by Jones-S** [bpostlethwaite/colormap#1]
Hey there
I just found your colormap repo here and I want to use it to display color tints depending on some data input. Not sure if I'm getting the right thing here, but I guess so.

Well, anyway, I just wanted to ask, if there is a way to use colormap without browserify. What does it actually require?
Can I also load the important stuff manually?

Thanks for your answer.

cheers

**Comment by vladh** [comment]
```bash
browserify -s colormap index.js > colormap.js
```
