### ISSUE TITLE
Where can I get the .js ?

### ISSUE THREAD

**Issue by japhigu** [bpostlethwaite/colormap#10]
I merely want to use this to generate a colormap with 10 divisions using the "Jet" palette.

But this isn't javascript, this is some node BS with requirements that I cannot find seperately !

I want one .js file containing what this git repo is supposed to be doing - how do I get that ?

**Comment by japhigu** [comment]
I think I get it - I need to browserify this shit. And the OP dares call this a release ? Just put the damn bundled edition in a separate folder FFS.

**Comment by bpostlethwaite** [comment]
once you make a bundle why don't you make a PR so that others can share your great work!

**Comment by unional** [comment]
There is a `globalify` (or my `@unional/globlaify` which use webpack and the file size is smaller) to create a single js file for script usage.

```sh
npm i -g globalify
# or npm i -g @unional/globalify

# generates colormap.js
globalify colormap
```
