### ISSUE TITLE
Reduce library size

### ISSUE THREAD

**Issue by unional** [bpostlethwaite/colormap#13]
`colormap` is great but including `arraytools` and `clone` make the library quite large (total to ~200k not minified using `webpack`. Minified along with `rollup` would be smaller).

I created [`color-map`](https://github.com/unional/color-map) which create the color range same as your inner loop without dependency.

It is (1k minified, was 10k not minified using `webpack`). Do you want to use it inside your library?

**Comment by bpostlethwaite** [comment]
Yep absolutely. @dfcreative will probably address this in an upcoming version. No reason for this module to be stupidly huge.

**Comment by bpostlethwaite** [comment]
solved in #15
