### ISSUE TITLE
'#aNaNaN' colors returned with small (but acceptable) nshades

### ISSUE THREAD

**Issue by vladh** [bpostlethwaite/colormap#2]
```javascript
> colormap({colormap: 'YIGnBu', nshades: 12})
[ '#081d58',
  '#253494',
  '#aNaNaN',
  '#225ea8',
  '#1d91c0',
  '#aNaNaN',
  '#41b6c4',
  '#7fcdbb',
  '#aNaNaN',
  '#c7e9b4',
  '#edf8d9',
  '#aNaNaN' ]
```

The minimum number of colors should be updated or the code altered to allow fewer shades — it is stated that the minimum for YIGnBu is 9.

Thanks.

**Comment by vladh** [comment]
This is caused by [arraytools issue #1](https://github.com/bpostlethwaite/arraytools/issues/1).

**Comment by bpostlethwaite** [comment]
wow I totally missed these issue! Super sorry.

**Comment by bpostlethwaite** [comment]
fixed in arraytools and bumped dep version here. Thanks!
