### ISSUE TITLE
Guide for importing in a frond end app?

### ISSUE THREAD

**Issue by M94antony** [bpostlethwaite/colormap#20]
Can't seem to find the dist file ? colormap.js ? guide is pretty bare.
Any help appreciated thanks.

**Comment by bpostlethwaite** [comment]
Right there is no dist. I'll try and update the build of this module so it has some more modern practices.

**Comment by bpostlethwaite** [comment]
also yes, the documentation is sparse. I've slated to do a little work in this lib soon
