### ISSUE TITLE
How is the index value in the colorscale.js calculated/selected for each colormap?

### ISSUE THREAD

**Issue by hkundnani** [bpostlethwaite/colormap#25]
I want to add a new colormap turbo to the colormap module but I don't understand how the current colorscale was choosen/calculated and how to generate same for turbo colormap. If you could explain or direct me to some document that would be really helpful. Thanks.

**Comment by bpostlethwaite** [comment]
If I remember correctly we are just doing linear interpolations along a set of selected points for each of the rgb scales.
Logic is in https://github.com/bpostlethwaite/colormap/blob/master/index.js

So the input should be a set of rgb values with an index (between 0-1) like these examples: https://github.com/bpostlethwaite/colormap/blob/master/colorScale.js

I'll get around to Turbo soon though https://github.com/bpostlethwaite/colormap/issues/24
