### ISSUE TITLE
Alpha values are reused for color maps with the same name

### ISSUE THREAD

**Issue by Lugribossk** [bpostlethwaite/colormap#3]
The alpha value used the first time when generating a color map is reused when generating more maps with the same name, even if they specify different values. E.g.:
```javascript
var blueRed = colormap({
    colormap: "bluered",
    format: "rgba",
    alpha: [0, 1]
});

var blueRed2 = colormap({
    colormap: "bluered",
    format: "rgba",
    alpha: [0, 0.5]
});

console.log(blueRed[blueRed.length - 1]); // [ 255, 0, 0, 1 ]
console.log(blueRed2[blueRed2.length - 1]); // Also [ 255, 0, 0, 1 ] but should be [ 255, 0, 0, 0.5 ]
```

**Comment by bpostlethwaite** [comment]
Thanks for the report. Fixing right now. Sorry for the delay. Apparently I am not receiving or somehow totally missed email updates for this repo

**Comment by Lugribossk** [comment]
Great, thanks for fixing that!
