### ISSUE TITLE
Parula viridis magma plasma inferno

### ISSUE THREAD

**Issue by dfcreative** [bpostlethwaite/colormap#5]
Hi @bpostlethwaite!

There are additional sweet color maps

* [matplotlib here](https://github.com/d3/d3-scale#sequential-color-scales).
* [beautiful oceanography colormaps](http://matplotlib.org/cmocean/)
* [cosine gradient](https://github.com/vorg/cosine-gradient), [2](http://dev.thi.ng/gradients/), [3](https://github.com/thi-ng/color/blob/master/src/gradients.org)
* [scale-color-perceptual](https://github.com/politiken-journalism/scale-color-perceptual)
* [palette.js](http://google.github.io/palette.js/)

I’m thinking to make a PR, so just leave notice here :)

**Comment by bpostlethwaite** [comment]
The more colormaps the better and PRs are very welcome. Let me know if I can be of any assistance.

**Comment by bpostlethwaite** [comment]
perhaps of interest https://github.com/politiken-journalism/scale-color-perceptual

**Comment by dfcreative** [comment]
Ahha, that is the repository I was looking for yesterday, thank you

**Comment by dfcreative** [comment]
@bpostlethwaite check it out, I used colormap with [gl-spectrum here](https://audio-lab.github.io/gl-spectrum/).
Thinking to implement new awesome schemes :)

**Comment by bpostlethwaite** [comment]
Hey that is really cool, nice stuff!

**Comment by bpostlethwaite** [comment]
Doubly appreciated as I am a Spectogram nerd - coming over from the seismic sciences :)

**Comment by dfcreative** [comment]
Yeah, spectrogram is next in my list hehe)

**Comment by dfcreative** [comment]
I’ve made a #6 related to this. Everything abovementioned is implemented, except for cosine gradients, which are rather beautiful than useful.
